export interface ICD10Code {
  code: string;
  label: string;
}

export type IcdCategoryKey =
  | "infectious"
  | "endocrine"
  | "mental_health"
  | "neuro"
  | "ent_eye"
  | "cardio"
  | "respiratory"
  | "gi"
  | "gu"
  | "obstetric"
  | "musculoskeletal"
  | "skin"
  | "trauma_injury"
  | "external_causes"
  | "symptoms"
  | "followup_zcodes";

export function inferIcd10Category(code: string): IcdCategoryKey {
  const c = (code || "").toUpperCase();
  if (c.startsWith("S") || c.startsWith("T")) return "trauma_injury";
  if (c.startsWith("V") || c.startsWith("W") || c.startsWith("X") || c.startsWith("Y")) {
    return "external_causes";
  }
  if (c.startsWith("A") || c.startsWith("B")) return "infectious";
  if (c.startsWith("E")) return "endocrine";
  if (c.startsWith("F")) return "mental_health";
  if (c.startsWith("G")) return "neuro";
  if (c.startsWith("H")) return "ent_eye";
  if (c.startsWith("I")) return "cardio";
  if (c.startsWith("J")) return "respiratory";
  if (c.startsWith("K")) return "gi";
  if (c.startsWith("N")) return "gu";
  if (c.startsWith("O")) return "obstetric";
  if (c.startsWith("M")) return "musculoskeletal";
  if (c.startsWith("L")) return "skin";
  if (c.startsWith("R")) return "symptoms";
  if (c.startsWith("Z")) return "followup_zcodes";
  return "symptoms";
}

// Curated set for performance + realism in this simulation.
export const ICD10_CODES: ICD10Code[] = [
  // Infectious disease
  { code: "A08.4", label: "Viral intestinal infection, unspecified" },
  { code: "A09", label: "Infectious gastroenteritis and colitis, unspecified" },
  { code: "A41.9", label: "Sepsis, unspecified organism" },
  { code: "A49.9", label: "Bacterial infection, unspecified" },
  { code: "B34.9", label: "Viral infection, unspecified" },
  { code: "B37.3", label: "Candidiasis of vulva and vagina" },
  { code: "B86", label: "Scabies" },
  { code: "B97.29", label: "Other coronavirus as the cause of diseases classified elsewhere" },

  // Endocrine/metabolic
  { code: "E03.9", label: "Hypothyroidism, unspecified" },
  { code: "E11.9", label: "Type 2 diabetes mellitus without complications" },
  { code: "E11.65", label: "Type 2 diabetes mellitus with hyperglycemia" },
  { code: "E10.9", label: "Type 1 diabetes mellitus without complications" },
  { code: "E16.2", label: "Hypoglycemia, unspecified" },
  { code: "E66.9", label: "Obesity, unspecified" },
  { code: "E78.5", label: "Hyperlipidemia, unspecified" },
  { code: "E87.1", label: "Hypo-osmolality and hyponatremia" },
  { code: "E87.6", label: "Hypokalemia" },
  { code: "E86.0", label: "Dehydration" },

  // Mental/behavioral
  { code: "F10.10", label: "Alcohol abuse, uncomplicated" },
  { code: "F11.20", label: "Opioid dependence, uncomplicated" },
  { code: "F12.90", label: "Cannabis use, unspecified, uncomplicated" },
  { code: "F17.210", label: "Nicotine dependence, cigarettes, uncomplicated" },
  { code: "F20.9", label: "Schizophrenia, unspecified" },
  { code: "F31.9", label: "Bipolar disorder, unspecified" },
  { code: "F32.A", label: "Depression, unspecified" },
  { code: "F33.1", label: "Major depressive disorder, recurrent, moderate" },
  { code: "F41.1", label: "Generalized anxiety disorder" },
  { code: "F41.9", label: "Anxiety disorder, unspecified" },
  { code: "F43.10", label: "Post-traumatic stress disorder, unspecified" },
  { code: "F90.9", label: "Attention-deficit hyperactivity disorder, unspecified type" },
  { code: "R45.851", label: "Suicidal ideations" },
  { code: "T14.91XA", label: "Suicide attempt, initial encounter" },

  // Nervous system
  { code: "G40.909", label: "Epilepsy, unspecified, not intractable, without status epilepticus" },
  { code: "G43.909", label: "Migraine, unspecified, not intractable, without status migrainosus" },
  { code: "G44.209", label: "Tension-type headache, unspecified, not intractable" },
  { code: "G47.00", label: "Insomnia, unspecified" },
  { code: "G62.9", label: "Polyneuropathy, unspecified" },
  { code: "G93.40", label: "Encephalopathy, unspecified" },
  { code: "R42", label: "Dizziness and giddiness" },
  { code: "R51.9", label: "Headache, unspecified" },

  // Eye/ENT
  { code: "H10.9", label: "Conjunctivitis, unspecified" },
  { code: "H66.90", label: "Otitis media, unspecified, unspecified ear" },
  { code: "H81.10", label: "Benign paroxysmal vertigo, unspecified ear" },
  { code: "J01.90", label: "Acute sinusitis, unspecified" },
  { code: "J02.9", label: "Acute pharyngitis, unspecified" },
  { code: "J03.90", label: "Acute tonsillitis, unspecified" },
  { code: "J04.0", label: "Acute laryngitis" },

  // Cardiovascular
  { code: "I10", label: "Essential (primary) hypertension" },
  { code: "I16.0", label: "Hypertensive urgency" },
  { code: "I20.9", label: "Angina pectoris, unspecified" },
  { code: "I21.4", label: "Non-ST elevation myocardial infarction" },
  { code: "I25.10", label: "Atherosclerotic heart disease of native coronary artery without angina pectoris" },
  { code: "I26.99", label: "Other pulmonary embolism without acute cor pulmonale" },
  { code: "I48.91", label: "Unspecified atrial fibrillation" },
  { code: "I50.9", label: "Heart failure, unspecified" },
  { code: "I63.9", label: "Cerebral infarction, unspecified" },
  { code: "I95.9", label: "Hypotension, unspecified" },
  { code: "R00.0", label: "Tachycardia, unspecified" },
  { code: "R07.2", label: "Precordial pain" },
  { code: "R07.9", label: "Chest pain, unspecified" },
  { code: "R55", label: "Syncope and collapse" },
  { code: "Z86.73", label: "Personal history of transient ischemic attack and cerebral infarction without residual deficits" },

  // Respiratory
  { code: "J00", label: "Acute nasopharyngitis (common cold)" },
  { code: "J06.9", label: "Acute upper respiratory infection, unspecified" },
  { code: "J09.X2", label: "Influenza due to identified novel influenza A virus with other respiratory manifestations" },
  { code: "J11.1", label: "Influenza due to unidentified influenza virus with other respiratory manifestations" },
  { code: "J12.9", label: "Viral pneumonia, unspecified" },
  { code: "J18.9", label: "Pneumonia, unspecified organism" },
  { code: "J20.9", label: "Acute bronchitis, unspecified" },
  { code: "J44.1", label: "Chronic obstructive pulmonary disease with acute exacerbation" },
  { code: "J45.901", label: "Unspecified asthma with (acute) exacerbation" },
  { code: "J45.909", label: "Unspecified asthma, uncomplicated" },
  { code: "J96.00", label: "Acute respiratory failure, unspecified whether with hypoxia or hypercapnia" },
  { code: "R05.9", label: "Cough, unspecified" },
  { code: "R06.00", label: "Dyspnea, unspecified" },
  { code: "R06.02", label: "Shortness of breath" },
  { code: "R09.81", label: "Nasal congestion" },

  // GI/hepatobiliary
  { code: "K21.9", label: "Gastro-esophageal reflux disease without esophagitis" },
  { code: "K29.70", label: "Gastritis, unspecified, without bleeding" },
  { code: "K35.80", label: "Unspecified acute appendicitis" },
  { code: "K52.9", label: "Noninfective gastroenteritis and colitis, unspecified" },
  { code: "K56.609", label: "Unspecified intestinal obstruction, unspecified as to partial versus complete obstruction" },
  { code: "K57.92", label: "Diverticulitis of intestine, part unspecified, without perforation or abscess without bleeding" },
  { code: "K59.00", label: "Constipation, unspecified" },
  { code: "K62.5", label: "Hemorrhage of anus and rectum" },
  { code: "K64.9", label: "Unspecified hemorrhoids" },
  { code: "K70.30", label: "Alcoholic cirrhosis of liver without ascites" },
  { code: "K74.60", label: "Unspecified cirrhosis of liver" },
  { code: "K80.20", label: "Calculus of gallbladder without cholecystitis without obstruction" },
  { code: "K81.0", label: "Acute cholecystitis" },
  { code: "K85.90", label: "Acute pancreatitis, unspecified" },
  { code: "R10.11", label: "Right upper quadrant pain" },
  { code: "R10.13", label: "Epigastric pain" },
  { code: "R10.31", label: "Right lower quadrant pain" },
  { code: "R10.32", label: "Left lower quadrant pain" },
  { code: "R10.9", label: "Unspecified abdominal pain" },
  { code: "R11.0", label: "Nausea" },
  { code: "R11.10", label: "Vomiting, unspecified" },
  { code: "R11.2", label: "Nausea with vomiting, unspecified" },
  { code: "R19.7", label: "Diarrhea, unspecified" },

  // GU/renal/reproductive
  { code: "N17.9", label: "Acute kidney failure, unspecified" },
  { code: "N18.9", label: "Chronic kidney disease, unspecified" },
  { code: "N20.0", label: "Calculus of kidney" },
  { code: "N23", label: "Unspecified renal colic" },
  { code: "N39.0", label: "Urinary tract infection, site not specified" },
  { code: "N39.3", label: "Stress incontinence (female) (male)" },
  { code: "N40.1", label: "Benign prostatic hyperplasia with lower urinary tract symptoms" },
  { code: "N45.1", label: "Epididymitis" },
  { code: "N76.0", label: "Acute vaginitis" },
  { code: "N93.9", label: "Abnormal uterine and vaginal bleeding, unspecified" },
  { code: "R30.0", label: "Dysuria" },
  { code: "R31.9", label: "Hematuria, unspecified" },
  { code: "R33.9", label: "Retention of urine, unspecified" },

  // Obstetric
  { code: "O21.9", label: "Vomiting of pregnancy, unspecified" },
  { code: "O26.899", label: "Other specified pregnancy related conditions, unspecified trimester" },
  { code: "O80", label: "Encounter for full-term uncomplicated delivery" },
  { code: "Z32.01", label: "Encounter for pregnancy test, result positive" },
  { code: "Z34.90", label: "Encounter for supervision of normal pregnancy, unspecified, unspecified trimester" },

  // Musculoskeletal
  { code: "M25.511", label: "Pain in right shoulder" },
  { code: "M25.512", label: "Pain in left shoulder" },
  { code: "M25.561", label: "Pain in right knee" },
  { code: "M25.562", label: "Pain in left knee" },
  { code: "M54.2", label: "Cervicalgia" },
  { code: "M54.50", label: "Low back pain, unspecified" },
  { code: "M54.6", label: "Pain in thoracic spine" },
  { code: "M62.830", label: "Muscle spasm of back" },
  { code: "M79.1", label: "Myalgia" },
  { code: "M79.671", label: "Pain in right foot" },
  { code: "M79.672", label: "Pain in left foot" },
  { code: "M10.9", label: "Gout, unspecified" },
  { code: "M19.90", label: "Unspecified osteoarthritis, unspecified site" },

  // Skin
  { code: "L02.91", label: "Cutaneous abscess, unspecified" },
  { code: "L03.90", label: "Cellulitis, unspecified" },
  { code: "L20.9", label: "Atopic dermatitis, unspecified" },
  { code: "L23.9", label: "Allergic contact dermatitis, unspecified cause" },
  { code: "L29.9", label: "Pruritus, unspecified" },
  { code: "L50.9", label: "Urticaria, unspecified" },
  { code: "L70.0", label: "Acne vulgaris" },
  { code: "R21", label: "Rash and other nonspecific skin eruption" },

  // Symptoms/general
  { code: "R41.82", label: "Altered mental status, unspecified" },
  { code: "R50.9", label: "Fever, unspecified" },
  { code: "R53.1", label: "Weakness" },
  { code: "R53.81", label: "Other malaise" },
  { code: "R53.83", label: "Other fatigue" },
  { code: "R60.0", label: "Localized edema" },
  { code: "R63.0", label: "Anorexia" },
  { code: "R63.4", label: "Abnormal weight loss" },
  { code: "R73.9", label: "Hyperglycemia, unspecified" },
  { code: "R79.89", label: "Other specified abnormal findings of blood chemistry" },

  // Injury/trauma
  { code: "S01.81XA", label: "Laceration without foreign body of other part of head, initial encounter" },
  { code: "S06.0X0A", label: "Concussion without loss of consciousness, initial encounter" },
  { code: "S09.90XA", label: "Unspecified injury of head, initial encounter" },
  { code: "S16.1XXA", label: "Strain of muscle, fascia and tendon at neck level, initial encounter" },
  { code: "S29.012A", label: "Strain of muscle and tendon of back wall of thorax, initial encounter" },
  { code: "S39.012A", label: "Strain of muscle, fascia and tendon of lower back, initial encounter" },
  { code: "S42.201A", label: "Unspecified fracture of upper end of right humerus, initial encounter for closed fracture" },
  { code: "S52.501A", label: "Unspecified fracture of lower end of right radius, initial encounter" },
  { code: "S62.101A", label: "Unspecified fracture of right wrist and hand, initial encounter for closed fracture" },
  { code: "S72.001A", label: "Fracture of unspecified part of neck of right femur, initial encounter for closed fracture" },
  { code: "S82.001A", label: "Fracture of right patella, initial encounter" },
  { code: "S82.101A", label: "Unspecified fracture of upper end of right tibia, initial encounter for closed fracture" },
  { code: "S91.301A", label: "Unspecified open wound, right foot, initial encounter" },
  { code: "T14.8XXA", label: "Other injury of unspecified body region, initial encounter" },
  { code: "T30.0", label: "Burn of unspecified body region, unspecified degree" },
  { code: "T50.901A", label: "Poisoning by unspecified drugs, medicaments and biological substances, accidental, initial encounter" },
  { code: "T63.441A", label: "Toxic effect of venom of bees, accidental, initial encounter" },

  // External causes
  { code: "V43.52XA", label: "Car driver injured in collision with sport utility vehicle in traffic accident, initial encounter" },
  { code: "W01.0XXA", label: "Fall on same level from slipping, tripping and stumbling without subsequent striking against object, initial encounter" },
  { code: "W10.9XXA", label: "Fall on and from stairs and steps, unspecified, initial encounter" },
  { code: "W19.XXXA", label: "Unspecified fall, initial encounter" },
  { code: "W54.0XXA", label: "Bitten by dog, initial encounter" },
  { code: "W55.01XA", label: "Bitten by cat, initial encounter" },
  { code: "X58.XXXA", label: "Exposure to other specified factors, initial encounter" },
  { code: "Y92.009", label: "Unspecified place in unspecified non-institutional residence as the place of occurrence of the external cause" },

  // Z-codes and follow-up
  { code: "Z00.00", label: "Encounter for general adult medical examination without abnormal findings" },
  { code: "Z09", label: "Encounter for follow-up examination after completed treatment for conditions other than malignant neoplasm" },
  { code: "Z13.1", label: "Encounter for screening for diabetes mellitus" },
  { code: "Z20.822", label: "Contact with and (suspected) exposure to COVID-19" },
  { code: "Z23", label: "Encounter for immunization" },
  { code: "Z51.89", label: "Encounter for other specified aftercare" },
  { code: "Z71.9", label: "Counseling, unspecified" },
  { code: "Z79.01", label: "Long term (current) use of anticoagulants" },
  { code: "Z79.4", label: "Long term (current) use of insulin" },
  { code: "Z87.891", label: "Personal history of nicotine dependence" },
  { code: "Z91.14", label: "Patient's other noncompliance with medication regimen" },
  { code: "Z91.81", label: "History of falling" },
  { code: "Z99.81", label: "Dependence on supplemental oxygen" },

  // Pediatric/common acute
  { code: "H65.93", label: "Unspecified nonsuppurative otitis media, bilateral" },
  { code: "J21.9", label: "Acute bronchiolitis, unspecified" },
  { code: "J35.1", label: "Hypertrophy of tonsils" },
  { code: "K00.7", label: "Teething syndrome" },
  { code: "R50.81", label: "Fever presenting with conditions classified elsewhere" },

  // Additional infectious
  { code: "A15.0", label: "Tuberculosis of lung" },
  { code: "A39.0", label: "Meningococcal meningitis" },
  { code: "A41.01", label: "Sepsis due to Methicillin susceptible Staphylococcus aureus" },
  { code: "A41.02", label: "Sepsis due to Methicillin resistant Staphylococcus aureus" },
  { code: "A49.02", label: "Methicillin resistant Staphylococcus aureus infection, unspecified" },
  { code: "B00.9", label: "Herpes simplex infection, unspecified" },
  { code: "B02.9", label: "Zoster without complications" },
  { code: "B18.2", label: "Chronic viral hepatitis C without hepatic coma" },
  { code: "B19.20", label: "Unspecified viral hepatitis C without hepatic coma" },
  { code: "B34.2", label: "Coronavirus infection, unspecified" },
  { code: "B37.0", label: "Candidal stomatitis" },
  { code: "B96.21", label: "Unspecified E coli as cause of diseases classified elsewhere" },
  { code: "B99.9", label: "Unspecified infectious disease" },

  // Additional endocrine/metabolic
  { code: "E05.00", label: "Thyrotoxicosis with diffuse goiter without thyrotoxic crisis" },
  { code: "E11.21", label: "Type 2 diabetes mellitus with diabetic nephropathy" },
  { code: "E11.22", label: "Type 2 diabetes mellitus with chronic kidney disease" },
  { code: "E11.29", label: "Type 2 diabetes mellitus with other specified kidney complication" },
  { code: "E11.65", label: "Type 2 diabetes mellitus with hyperglycemia" },
  { code: "E78.00", label: "Pure hypercholesterolemia, unspecified" },
  { code: "E78.01", label: "Familial hypercholesterolemia, unspecified" },
  { code: "E78.2", label: "Mixed hyperlipidemia" },
  { code: "E78.41", label: "Elevated lipoproteins" },
  { code: "E83.40", label: "Disorders of magnesium metabolism, unspecified" },
  { code: "E86.1", label: "Hypovolemia" },
  { code: "E87.0", label: "Hyperosmolality and hypernatremia" },
  { code: "E87.2", label: "Acidosis" },
  { code: "E87.3", label: "Alkalosis" },
  { code: "E88.81", label: "Metabolic syndrome" },

  // Additional mental/behavioral
  { code: "F10.20", label: "Alcohol dependence, uncomplicated" },
  { code: "F10.99", label: "Alcohol use, unspecified with unspecified alcohol-induced disorder" },
  { code: "F11.10", label: "Heroin use, uncomplicated" },
  { code: "F17.200", label: "Nicotine dependence, unspecified, uncomplicated" },
  { code: "F19.10", label: "Other psychoactive substance use, uncomplicated" },
  { code: "F20.0", label: "Paranoid schizophrenia" },
  { code: "F31.30", label: "Bipolar disorder, current episode manic, mild" },
  { code: "F31.81", label: "Bipolar II disorder" },
  { code: "F32.0", label: "Major depressive disorder, single episode, mild" },
  { code: "F32.1", label: "Major depressive disorder, single episode, moderate" },
  { code: "F32.2", label: "Major depressive disorder, single episode, severe without psychotic features" },
  { code: "F32.3", label: "Major depressive disorder, single episode, severe with psychotic features" },
  { code: "F32.4", label: "Major depressive disorder, single episode in partial remission" },
  { code: "F32.5", label: "Major depressive disorder, single episode in full remission" },
  { code: "F33.0", label: "Major depressive disorder, recurrent, mild" },
  { code: "F33.2", label: "Major depressive disorder, recurrent severe without psychotic features" },
  { code: "F40.00", label: "Agoraphobia, unspecified" },
  { code: "F40.10", label: "Social phobia, unspecified" },
  { code: "F41.0", label: "Panic disorder without agoraphobia" },
  { code: "F41.3", label: "Other mixed anxiety disorders" },
  { code: "F42.2", label: "Mixed obsessional thoughts and acts" },
  { code: "F43.0", label: "Acute stress reaction" },
  { code: "F43.12", label: "Post-traumatic stress disorder, chronic" },
  { code: "F43.21", label: "Adjustment disorder with depressed mood" },
  { code: "F44.0", label: "Dissociative amnesia" },
  { code: "F45.41", label: "Pain disorder with related psychological factors" },
  { code: "F48.9", label: "Nonpsychotic mental disorder, unspecified" },
  { code: "F70", label: "Mild intellectual disabilities" },
  { code: "F79", label: "Unspecified intellectual disabilities" },
  { code: "F84.0", label: "Autistic disorder" },
  { code: "F84.9", label: "Pervasive developmental disorder, unspecified" },

  // Additional nervous system
  { code: "G40.001", label: "Localization-related epilepsy, idiopathic, intractable, with status epilepticus" },
  { code: "G40.109", label: "Localization-related epilepsy, symptomatic, not intractable, without status epilepticus" },
  { code: "G43.001", label: "Migraine without aura, not intractable, with status migrainosus" },
  { code: "G43.709", label: "Chronic migraine without aura, not intractable, without status migrainosus" },
  { code: "G44.209", label: "Tension-type headache, unspecified, not intractable" },
  { code: "G45.9", label: "Transient cerebral ischemic attack, unspecified" },
  { code: "G47.33", label: "Sleep apnea, unspecified" },
  { code: "G54.6", label: "Phantom limb syndrome with pain" },
  { code: "G56.00", label: "Carpal tunnel syndrome, unspecified upper limb" },
  { code: "G57.30", label: "Lesion of lateral popliteal nerve, unspecified lower limb" },
  { code: "G89.0", label: "Central pain syndrome" },
  { code: "G89.11", label: "Acute pain due to trauma" },
  { code: "G89.21", label: "Chronic pain due to trauma" },
  { code: "G89.29", label: "Other chronic pain" },

  // Additional cardiovascular
  { code: "I11.0", label: "Hypertensive heart disease with heart failure" },
  { code: "I25.110", label: "Atherosclerotic heart disease of native coronary artery with unstable angina pectoris" },
  { code: "I25.700", label: "Atherosclerosis of coronary artery bypass graft(s), unspecified" },
  { code: "I34.0", label: "Nonrheumatic mitral (valve) insufficiency" },
  { code: "I35.0", label: "Nonrheumatic aortic (valve) stenosis" },
  { code: "I48.11", label: "Long standing persistent atrial fibrillation" },
  { code: "I48.19", label: "Other persistent atrial fibrillation" },
  { code: "I50.20", label: "Systolic dysfunction, unspecified" },
  { code: "I50.30", label: "Unspecified diastolic (congestive) heart failure" },
  { code: "I50.32", label: "Chronic diastolic heart failure" },
  { code: "I63.50", label: "Cerebral infarction due to unspecified occlusion or stenosis of vertebral arteries" },
  { code: "I63.9", label: "Cerebral infarction, unspecified" },
  { code: "I69.351", label: "Sequelae of cerebral infarction, left-sided hemiplegia" },
  { code: "I74.3", label: "Embolism and thrombosis of arteries of the lower extremities" },
  { code: "I80.219", label: "Phlebitis and thrombophlebitis of unspecified deep vessels of lower extremities" },
  { code: "I80.229", label: "Phlebitis and thrombophlebitis of unspecified deep vessels of left lower extremity" },
  { code: "I82.409", label: "Acute embolism and thrombosis of unspecified deep veins of unspecified lower extremity" },
  { code: "I82.90", label: "Acute embolism and thrombosis of unspecified vein" },

  // Additional respiratory
  { code: "J02.0", label: "Streptococcal pharyngitis" },
  { code: "J06.9", label: "Acute upper respiratory infection, unspecified" },
  { code: "J12.81", label: "Pneumonia due to SARS-associated coronavirus" },
  { code: "J12.89", label: "Other viral pneumonia" },
  { code: "J13", label: "Pneumonia due to Streptococcus pneumoniae" },
  { code: "J14", label: "Pneumonia due to Haemophilus influenzae" },
  { code: "J15.211", label: "Pneumonia due to Methicillin susceptible Staphylococcus aureus" },
  { code: "J15.212", label: "Pneumonia due to Methicillin resistant Staphylococcus aureus" },
  { code: "J15.9", label: "Unspecified bacterial pneumonia" },
  { code: "J18.1", label: "Lobar pneumonia, unspecified organism" },
  { code: "J18.9", label: "Pneumonia, unspecified organism" },
  { code: "J20.0", label: "Acute bronchitis due to Mycoplasma pneumoniae" },
  { code: "J20.5", label: "Acute bronchitis due to respiratory syncytial virus" },
  { code: "J22", label: "Unspecified acute lower respiratory infection" },
  { code: "J40", label: "Bronchitis, not specified as acute or chronic" },
  { code: "J44.0", label: "COPD with acute lower respiratory infection" },
  { code: "J44.9", label: "COPD, unspecified" },
  { code: "J45.20", label: "Mild intermittent asthma, uncomplicated" },
  { code: "J45.30", label: "Mild persistent asthma, uncomplicated" },
  { code: "J45.40", label: "Moderate persistent asthma, uncomplicated" },
  { code: "J45.50", label: "Severe persistent asthma, uncomplicated" },
  { code: "J69.0", label: "Pneumonitis due to inhalation of food and vomit" },
  { code: "J84.10", label: "Pulmonary fibrosis, unspecified" },
  { code: "J96.01", label: "Acute respiratory failure with hypoxia" },
  { code: "J96.11", label: "Chronic respiratory failure with hypoxia" },
  { code: "J96.91", label: "Respiratory failure, unspecified with hypoxia" },

  // Additional GI
  { code: "K21.0", label: "Gastro-esophageal reflux disease with esophagitis" },
  { code: "K25.0", label: "Acute gastric ulcer with hemorrhage" },
  { code: "K25.4", label: "Chronic or unspecified gastric ulcer with hemorrhage" },
  { code: "K26.0", label: "Acute duodenal ulcer with hemorrhage" },
  { code: "K29.00", label: "Acute gastritis without bleeding" },
  { code: "K29.70", label: "Gastritis, unspecified, without bleeding" },
  { code: "K35.80", label: "Unspecified acute appendicitis" },
  { code: "K57.30", label: "Unspecified diverticulitis of large intestine without perforation or abscess without bleeding" },
  { code: "K59.1", label: "Functional diarrhea" },
  { code: "K63.5", label: "Polyp of colon" },
  { code: "K80.00", label: "Calculus of gallbladder with acute cholecystitis without obstruction" },
  { code: "K80.65", label: "Calculus of gallbladder and bile duct with chronic cholecystitis with obstruction" },
  { code: "K81.9", label: "Cholecystitis, unspecified" },
  { code: "K83.0", label: "Cholangitis" },
  { code: "K85.90", label: "Acute pancreatitis, unspecified" },
  { code: "K86.81", label: "Exocrine pancreatic insufficiency" },
  { code: "K92.0", label: "Hematemesis" },
  { code: "K92.1", label: "Melena" },
  { code: "K92.2", label: "Gastrointestinal hemorrhage, unspecified" },

  // Additional GU/renal
  { code: "N17.0", label: "Acute kidney failure with tubular necrosis" },
  { code: "N17.1", label: "Acute kidney failure with acute cortical necrosis" },
  { code: "N17.2", label: "Acute kidney failure with medullary necrosis" },
  { code: "N18.1", label: "Chronic kidney disease, stage 1" },
  { code: "N18.2", label: "Chronic kidney disease, stage 2" },
  { code: "N18.3", label: "Chronic kidney disease, stage 3a" },
  { code: "N18.30", label: "Chronic kidney disease, stage 3 unspecified" },
  { code: "N18.4", label: "Chronic kidney disease, stage 4" },
  { code: "N18.5", label: "Chronic kidney disease, stage 5" },
  { code: "N18.6", label: "End stage renal disease" },
  { code: "N18.9", label: "Chronic kidney disease, unspecified" },
  { code: "N19", label: "Unspecified kidney failure" },
  { code: "N20.0", label: "Calculus of kidney" },
  { code: "N20.1", label: "Calculus of ureter" },
  { code: "N21.0", label: "Calculus in bladder" },
  { code: "N30.00", label: "Acute cystitis without hematuria" },
  { code: "N30.01", label: "Acute cystitis with hematuria" },
  { code: "N39.0", label: "Urinary tract infection, site not specified" },
  { code: "N39.1", label: "Persistent proteinuria, unspecified" },
  { code: "N39.3", label: "Stress incontinence (female) (male)" },
  { code: "N40.0", label: "Benign prostatic hyperplasia without lower urinary tract symptoms" },
  { code: "N41.0", label: "Acute prostatitis" },
  { code: "N41.1", label: "Chronic prostatitis" },
  { code: "N43.40", label: "Encysted hydrocele of tunica vaginalis, unspecified" },
  { code: "N47.1", label: "Hypertrophy of prepuce, neonatal" },
  { code: "N50.811", label: "Right testicular pain" },
  { code: "N73.0", label: "Acute parametritis and pelvic cellulitis" },
  { code: "N76.0", label: "Acute vaginitis" },
  { code: "N76.1", label: "Subacute and chronic vaginitis" },
  { code: "N80.0", label: "Endometriosis of uterus" },
  { code: "N92.0", label: "Excessive and frequent menstruation with regular cycle" },
  { code: "N93.9", label: "Abnormal uterine and vaginal bleeding, unspecified" },

  // Additional trauma/injury (S/T codes)
  { code: "S00.03XA", label: "Contusion of scalp, initial encounter" },
  { code: "S00.81XA", label: "Abrasion of other part of head, initial encounter" },
  { code: "S01.00XA", label: "Unspecified open wound of scalp, initial encounter" },
  { code: "S01.01XA", label: "Laceration without foreign body of scalp, initial encounter" },
  { code: "S02.0XXA", label: "Fracture of vault of skull, initial encounter" },
  { code: "S02.1XXA", label: "Fracture of base of skull, initial encounter" },
  { code: "S06.0X0A", label: "Concussion without loss of consciousness, initial encounter" },
  { code: "S06.0X1A", label: "Concussion with loss of consciousness of 30 minutes or less, initial encounter" },
  { code: "S06.0X9A", label: "Concussion with loss of consciousness of unspecified duration, initial encounter" },
  { code: "S10.01XA", label: "Contusion of throat, initial encounter" },
  { code: "S12.000A", label: "Unspecified fracture of first cervical vertebra, initial encounter for closed fracture" },
  { code: "S13.100A", label: "Unspecified subluxation of unspecified cervical vertebrae, initial encounter" },
  { code: "S22.020A", label: "Unstable burst fracture of T1-T6 vertebra, initial encounter for closed fracture" },
  { code: "S24.101A", label: "Unspecified injury at T1 level of thoracic spinal cord, initial encounter" },
  { code: "S32.002A", label: "Unspecified fracture of unspecified lumbar vertebra, initial encounter for closed fracture" },
  { code: "S42.001A", label: "Unspecified fracture of upper end of right clavicle, initial encounter for closed fracture" },
  { code: "S42.101A", label: "Unspecified fracture of upper end of right humerus, initial encounter for closed fracture" },
  { code: "S42.254A", label: "Nondisplaced comminuted fracture of shaft of right humerus, initial encounter for closed fracture" },
  { code: "S52.201A", label: "Unspecified fracture of shaft of right ulna, initial encounter for closed fracture" },
  { code: "S52.301A", label: "Unspecified fracture of shaft of right radius, initial encounter for closed fracture" },
  { code: "S52.501A", label: "Unspecified fracture of lower end of right radius, initial encounter" },
  { code: "S52.509A", label: "Unspecified fracture of lower end of unspecified radius, initial encounter" },
  { code: "S52.601A", label: "Unspecified fracture of lower end of right ulna, initial encounter" },
  { code: "S72.001A", label: "Fracture of unspecified part of neck of right femur, initial encounter" },
  { code: "S72.002A", label: "Fracture of unspecified part of neck of left femur, initial encounter" },
  { code: "S72.101A", label: "Unspecified trochanteric fracture of right femur, initial encounter for closed fracture" },
  { code: "S72.301A", label: "Unspecified fracture of shaft of right femur, initial encounter for closed fracture" },
  { code: "S72.402A", label: "Displaced fracture of lower epiphysis of right femur, initial encounter for closed fracture" },
  { code: "S82.001A", label: "Fracture of right patella, initial encounter" },
  { code: "S82.102A", label: "Displaced fracture of upper end of right tibia, initial encounter for closed fracture" },
  { code: "S82.201A", label: "Unspecified fracture of shaft of right tibia, initial encounter for closed fracture" },
  { code: "S82.301A", label: "Unspecified fracture of lower end of right tibia, initial encounter for closed fracture" },
  { code: "S82.401A", label: "Unspecified fracture of shaft of right fibula, initial encounter for closed fracture" },
  { code: "S82.601A", label: "Unspecified fracture of right lateral malleolus, initial encounter for closed fracture" },
  { code: "S82.891A", label: "Other fracture of right lower leg, initial encounter for closed fracture" },
  { code: "S92.001A", label: "Unspecified fracture of right calcaneus, initial encounter for closed fracture" },
  { code: "S92.101A", label: "Unspecified fracture of right talus, initial encounter for closed fracture" },
  { code: "T07", label: "Unspecified multiple injuries" },
  { code: "T14.0", label: "Superficial injury of unspecified body region" },
  { code: "T14.8", label: "Other injury of unspecified body region" },
  { code: "T14.90XA", label: "Unspecified injury, unspecified body region, initial encounter" },
  { code: "T20.00XA", label: "Burn of unspecified degree of head, face, and neck, unspecified site, initial encounter" },
  { code: "T21.00XA", label: "Burn of unspecified degree of trunk, unspecified site, initial encounter" },
  { code: "T22.00XA", label: "Burn of unspecified degree of unspecified site of right shoulder and upper limb" },
  { code: "T23.001A", label: "Burn of unspecified degree of right hand, unspecified site, initial encounter" },
  { code: "T24.00XA", label: "Burn of unspecified degree of unspecified site of right lower limb, except ankle and foot" },
  { code: "T25.00XA", label: "Burn of unspecified degree of unspecified site of right foot, initial encounter" },
  { code: "T33.01XA", label: "Superficial frostbite of right ear, initial encounter" },
  { code: "T66.XXXA", label: "Unspecified effects of radiation, initial encounter" },
  { code: "T73.0", label: "Starvation" },
  { code: "T73.1", label: "Deprivation of water" },
  { code: "T78.00XA", label: "Anaphylactic reaction due to unspecified food, initial encounter" },
  { code: "T78.1XXA", label: "Other adverse food reactions, not elsewhere classified, initial encounter" },
  { code: "T78.2XXA", label: "Anaphylactic shock, unspecified, initial encounter" },
  { code: "T78.40XA", label: "Allergy, unspecified, initial encounter" },
  { code: "T79.4XXA", label: "Shock, initial" },
  { code: "T80.1XXA", label: "Anaphylactic reaction due to serum, initial encounter" },
  { code: "T81.4XXA", label: "Sepsis following a procedure, initial encounter" },
  { code: "T82.838A", label: "Other specified complication of vascular dialysis catheter, initial encounter" },
  { code: "T83.110A", label: "Breakdown of incontinent device of urinary system, initial encounter" },
  { code: "T84.608A", label: "Infection and inflammatory reaction due to unspecified internal joint prosthesis" },
  { code: "T85.619A", label: "Breakdown of cardiac electrode, initial encounter" },
  { code: "T86.10", label: "Heart transplant rejection, unspecified" },
  { code: "T86.20", label: "Heart transplant failure" },
  { code: "T86.81", label: "Kidney transplant rejection" },
  { code: "T86.82", label: "Kidney transplant failure" },
  { code: "T88.1XXA", label: "Other adverse effects of drugs, medicaments and biological substances, initial encounter" },
  { code: "T88.6XXA", label: "Anaphylactic reaction due to adverse effect of correct drug or medicament properly administered, initial encounter" },
  { code: "T90.2XXA", label: "Sequelae of fracture of skull and facial bones, initial encounter" },
  { code: "T91.19XA", label: "Sequelae of other fracture of thorax, initial encounter" },
  { code: "T92.09XA", label: "Sequelae of unspecified injury of blood vessels of upper limb, initial encounter" },
  { code: "T93.89XA", label: "Sequelae of other specified injuries of unspecified lower leg, initial encounter" },

  // Additional external causes
  { code: "V00.01XA", label: "Pedestrian on foot injured in collision with roller-skater, initial encounter" },
  { code: "V03.90XA", label: "Pedestrian on foot injured in collision with unspecified car, traffic accident, initial encounter" },
  { code: "V12.99XA", label: "Pedestrian on foot injured in collision with other two- or three-wheeled motor vehicle, unspecified, traffic accident" },
  { code: "V18.01XA", label: "Person on outside of bus injured in collision with sport utility vehicle in traffic accident" },
  { code: "V30.01XA", label: "Driver of three-wheeled motor vehicle injured in collision with pedestrian or animal in traffic accident" },
  { code: "V43.12XA", label: "Car driver injured in collision with car in traffic accident" },
  { code: "V47.9XXA", label: "Unspecified car occupant injured in collision with unspecified motor vehicle in traffic accident" },
  { code: "V80.010A", label: "Driver of animal drawn vehicle injured in collision with pedestrian or animal" },
  { code: "V89.2XXA", label: "Person injured in unspecified motor-vehicle accident, traffic" },
  { code: "W00.0XXA", label: "Fall from non-in-line roller skates, initial encounter" },
  { code: "W01.0XXA", label: "Fall on same level from slipping, tripping and stumbling" },
  { code: "W10.0XXA", label: "Fall from, out of or through stairs and steps" },
  { code: "W18.01XA", label: "Fall from or off toilet, initial encounter" },
  { code: "W19.XXXA", label: "Unspecified fall, initial encounter" },
  { code: "W21.00XA", label: "Struck by hit or thrown ball, initial encounter" },
  { code: "W50.0XXA", label: "Struck by other person's hand, initial encounter" },
  { code: "W54.0XXA", label: "Bitten by dog, initial encounter" },
  { code: "X50.0XXA", label: "Overexertion from prolonged static or awkward postures" },
  { code: "X52.XXXA", label: "Prolonged stay in weightless environment, initial encounter" },
  { code: "X58.XXXA", label: "Exposure to other specified factors" },
  { code: "X71.XXXA", label: "Intentional self-harm by drowning and submersion" },
  { code: "X85", label: "Assault by other specified means" },
  { code: "Y92.009", label: "Unspecified place in unspecified non-institutional residence" },
  { code: "Y93.9", label: "Activity, unspecified" },

  // Additional symptoms (R codes)
  { code: "R00.00", label: "Tachycardia, unspecified" },
  { code: "R00.01", label: "Bradycardia, unspecified" },
  { code: "R04.2", label: "Blood-stained sputum" },
  { code: "R05.1", label: "Acute cough" },
  { code: "R05.2", label: "Subacute cough" },
  { code: "R05.3", label: "Chronic cough" },
  { code: "R06.01", label: "Orthopnea" },
  { code: "R06.03", label: "Acute respiratory distress" },
  { code: "R06.83", label: "Snoring" },
  { code: "R07.0", label: "Pain in throat" },
  { code: "R07.1", label: "Chest pain on breathing" },
  { code: "R07.81", label: "Pleurodynia" },
  { code: "R09.01", label: "Asphyxia" },
  { code: "R09.02", label: "Hypoxemia" },
  { code: "R10.0", label: "Acute abdomen" },
  { code: "R10.10", label: "Upper abdominal pain, unspecified" },
  { code: "R10.12", label: "Left upper quadrant pain" },
  { code: "R10.2", label: "Pelvic and perineal pain" },
  { code: "R10.4", label: "Other and unspecified abdominal pain" },
  { code: "R11.10", label: "Vomiting, unspecified" },
  { code: "R11.11", label: "Vomiting without nausea" },
  { code: "R11.12", label: "Vomiting of fecal matter" },
  { code: "R11.13", label: "Vomiting of blood" },
  { code: "R12", label: "Heartburn" },
  { code: "R14.0", label: "Abdominal distension (gaseous)" },
  { code: "R14.1", label: "Gas pain" },
  { code: "R14.2", label: "Flatulence" },
  { code: "R14.3", label: "Eructation" },
  { code: "R15.0", label: "Incomplete defecation" },
  { code: "R15.1", label: "Fecal smearing" },
  { code: "R15.9", label: "Full incontinence of feces" },
  { code: "R16.0", label: "Hepatomegaly, not elsewhere classified" },
  { code: "R16.1", label: "Splenomegaly, not elsewhere classified" },
  { code: "R17", label: "Unspecified jaundice" },
  { code: "R19.00", label: "Intra-abdominal and pelvic swelling, mass and lump, unspecified site" },
  { code: "R19.04", label: "Abdominal rigidity" },
  { code: "R19.05", label: "Right upper quadrant abdominal swelling, mass and lump" },
  { code: "R19.06", label: "Left upper quadrant abdominal swelling, mass and lump" },
  { code: "R19.07", label: "Right lower quadrant abdominal swelling, mass and lump" },
  { code: "R19.08", label: "Left lower quadrant abdominal swelling, mass and lump" },
  { code: "R20.0", label: "Anesthesia of skin" },
  { code: "R20.1", label: "Hypoesthesia of skin" },
  { code: "R20.2", label: "Paresthesia of skin" },
  { code: "R20.3", label: "Hyperesthesia" },
  { code: "R21", label: "Rash and other nonspecific skin eruption" },
  { code: "R25.0", label: "Abnormal head movements" },
  { code: "R25.1", label: "Tremor" },
  { code: "R25.2", label: "Cramp and spasm" },
  { code: "R25.8", label: "Other abnormal involuntary movements" },
  { code: "R26.0", label: "Ataxic gait" },
  { code: "R26.1", label: "Paralytic gait" },
  { code: "R26.81", label: "Unsteadiness on feet" },
  { code: "R26.89", label: "Other abnormalities of gait and mobility" },
  { code: "R29.6", label: "Repeated falls" },
  { code: "R29.810", label: "Facial weakness" },
  { code: "R29.818", label: "Other symptoms and signs involving the nervous system" },
  { code: "R30.0", label: "Dysuria" },
  { code: "R30.1", label: "Pelvic pain" },
  { code: "R31.0", label: "Gross hematuria" },
  { code: "R31.21", label: "Asymptomatic microscopic hematuria" },
  { code: "R31.29", label: "Other microscopic hematuria" },
  { code: "R32", label: "Unspecified urinary incontinence" },
  { code: "R33.0", label: "Retention of urine, unspecified" },
  { code: "R33.8", label: "Other retention of urine" },
  { code: "R34", label: "Unspecified anuria and oliguria" },
  { code: "R35.0", label: "Nocturia" },
  { code: "R35.1", label: "Nocturnal polyuria" },
  { code: "R35.81", label: "Nocturnal enuresis" },
  { code: "R39.11", label: "Hesitancy of micturition" },
  { code: "R39.12", label: "Poor urinary stream" },
  { code: "R39.13", label: "Splitting of urinary stream" },
  { code: "R39.14", label: "Feeling of incomplete bladder emptying" },
  { code: "R39.15", label: "Urgency of urination" },
  { code: "R39.16", label: "Straining to void" },
  { code: "R39.19", label: "Other difficulties with micturition" },
  { code: "R41.0", label: "Disorientation, unspecified" },
  { code: "R41.1", label: "Anterograde amnesia" },
  { code: "R41.2", label: "Retrograde amnesia" },
  { code: "R41.3", label: "Other amnesia" },
  { code: "R41.4", label: "Neurologic neglect syndrome" },
  { code: "R41.81", label: "Cognitive communication deficit" },
  { code: "R41.82", label: "Altered mental status, unspecified" },
  { code: "R41.83", label: "Personality change" },
  { code: "R42", label: "Dizziness and giddiness" },
  { code: "R43.0", label: "Anosmia" },
  { code: "R43.1", label: "Parosmia" },
  { code: "R43.2", label: "Parageusia" },
  { code: "R43.6", label: "Unspecified disturbances of smell and taste" },
  { code: "R45.0", label: "Nervousness" },
  { code: "R45.1", label: "Restlessness and agitation" },
  { code: "R45.2", label: "Unhappiness" },
  { code: "R45.3", label: "Demoralization and apathy" },
  { code: "R45.4", label: "Irritability and anger" },
  { code: "R45.6", label: "Physical violence" },
  { code: "R45.81", label: "Worried" },
  { code: "R45.82", label: "Anxious" },
  { code: "R46.0", label: "Very low level of personal hygiene" },
  { code: "R46.1", label: "Bizarre personal appearance" },
  { code: "R46.2", label: "Strange and inexplicable behavior" },
  { code: "R46.3", label: "Overactivity" },
  { code: "R46.4", label: "Slowness and poor responsiveness" },
  { code: "R46.5", label: "Suspicious and evasive manner" },
  { code: "R46.6", label: "Undue concern and preoccupation with stressful events" },
  { code: "R46.81", label: "Obsessive compulsive behavior" },
  { code: "R47.01", label: "Aphasia" },
  { code: "R47.02", label: "Dysphasia" },
  { code: "R47.1", label: "Dysarthria and anarthria" },
  { code: "R47.81", label: "Slurred speech" },
  { code: "R48.0", label: "Dyslexia and alexia" },
  { code: "R48.1", label: "Agnosia" },
  { code: "R48.2", label: "Apraxia" },
  { code: "R50.0", label: "Fever with chills" },
  { code: "R50.1", label: "Persistent fever" },
  { code: "R50.2", label: "Drug induced fever" },
  { code: "R50.9", label: "Fever, unspecified" },
  { code: "R51.9", label: "Headache, unspecified" },
  { code: "R52", label: "Pain, unspecified" },
  { code: "R53", label: "Malaise and fatigue" },
  { code: "R54", label: "Age-related physical debility" },
  { code: "R55", label: "Syncope and collapse" },
  { code: "R56.01", label: "Complex febrile convulsions" },
  { code: "R56.1", label: "Post traumatic seizures" },
  { code: "R56.9", label: "Unspecified convulsions" },
  { code: "R60.0", label: "Localized edema" },
  { code: "R60.1", label: "Generalized edema" },
  { code: "R61", label: "Generalized hyperhidrosis" },
  { code: "R62.0", label: "Delayed milestone in childhood" },
  { code: "R62.50", label: "Unspecified lack of expected normal physiological development" },
  { code: "R63.0", label: "Anorexia" },
  { code: "R63.1", label: "Polydipsia" },
  { code: "R63.2", label: "Polyphagia" },
  { code: "R63.3", label: "Feeding difficulties" },
  { code: "R63.4", label: "Abnormal weight loss" },
  { code: "R63.5", label: "Abnormal weight gain" },
  { code: "R64", label: "Cachexia" },
  { code: "R68.11", label: "Excessive crying of infant" },
  { code: "R68.12", label: "Excessive crying of child, adolescent or adult" },
  { code: "R68.2", label: "Dry mouth, unspecified" },
  { code: "R68.81", label: "Early satiety" },
  { code: "R68.82", label: "Decreased appetite" },
  { code: "R68.83", label: "Decreased libido" },
  { code: "R68.84", label: "Tiredness" },
  { code: "R70.0", label: "Elevated sedimentation rate" },
  { code: "R70.1", label: "Abnormal plasma viscosity" },
  { code: "R73.03", label: "Prediabetes" },
  { code: "R73.9", label: "Hyperglycemia, unspecified" },
  { code: "R75", label: "Inconclusive laboratory evidence of human immunodeficiency virus" },
  { code: "R79.0", label: "Abnormal level of blood mineral" },
  { code: "R79.1", label: "Abnormal coagulation profile" },
  { code: "R79.81", label: "Elevated C-reactive protein" },
  { code: "R79.82", label: "Elevated erythrocyte sedimentation rate" },
  { code: "R79.83", label: "Elevated prostate specific antigen" },
  { code: "R79.89", label: "Other specified abnormal findings of blood chemistry" },
];
