export interface ICD10Code {
  code: string;
  label: string;
}

// Curated set for performance + realism in this simulation.
export const ICD10_CODES: ICD10Code[] = [
  // Infectious disease
  { code: "A08.4", label: "Viral intestinal infection, unspecified" },
  { code: "A09", label: "Infectious gastroenteritis and colitis, unspecified" },
  { code: "A41.9", label: "Sepsis, unspecified organism" },
  { code: "A49.9", label: "Bacterial infection, unspecified" },
  { code: "B34.9", label: "Viral infection, unspecified" },
  { code: "B37.3", label: "Candidiasis of vulva and vagina" },
  { code: "B86", label: "Scabies" },
  { code: "B97.29", label: "Other coronavirus as the cause of diseases classified elsewhere" },

  // Endocrine/metabolic
  { code: "E03.9", label: "Hypothyroidism, unspecified" },
  { code: "E11.9", label: "Type 2 diabetes mellitus without complications" },
  { code: "E11.65", label: "Type 2 diabetes mellitus with hyperglycemia" },
  { code: "E10.9", label: "Type 1 diabetes mellitus without complications" },
  { code: "E16.2", label: "Hypoglycemia, unspecified" },
  { code: "E66.9", label: "Obesity, unspecified" },
  { code: "E78.5", label: "Hyperlipidemia, unspecified" },
  { code: "E87.1", label: "Hypo-osmolality and hyponatremia" },
  { code: "E87.6", label: "Hypokalemia" },
  { code: "E86.0", label: "Dehydration" },

  // Mental/behavioral
  { code: "F10.10", label: "Alcohol abuse, uncomplicated" },
  { code: "F11.20", label: "Opioid dependence, uncomplicated" },
  { code: "F12.90", label: "Cannabis use, unspecified, uncomplicated" },
  { code: "F17.210", label: "Nicotine dependence, cigarettes, uncomplicated" },
  { code: "F20.9", label: "Schizophrenia, unspecified" },
  { code: "F31.9", label: "Bipolar disorder, unspecified" },
  { code: "F32.A", label: "Depression, unspecified" },
  { code: "F33.1", label: "Major depressive disorder, recurrent, moderate" },
  { code: "F41.1", label: "Generalized anxiety disorder" },
  { code: "F41.9", label: "Anxiety disorder, unspecified" },
  { code: "F43.10", label: "Post-traumatic stress disorder, unspecified" },
  { code: "F90.9", label: "Attention-deficit hyperactivity disorder, unspecified type" },
  { code: "R45.851", label: "Suicidal ideations" },
  { code: "T14.91XA", label: "Suicide attempt, initial encounter" },

  // Nervous system
  { code: "G40.909", label: "Epilepsy, unspecified, not intractable, without status epilepticus" },
  { code: "G43.909", label: "Migraine, unspecified, not intractable, without status migrainosus" },
  { code: "G44.209", label: "Tension-type headache, unspecified, not intractable" },
  { code: "G47.00", label: "Insomnia, unspecified" },
  { code: "G62.9", label: "Polyneuropathy, unspecified" },
  { code: "G93.40", label: "Encephalopathy, unspecified" },
  { code: "R42", label: "Dizziness and giddiness" },
  { code: "R51.9", label: "Headache, unspecified" },

  // Eye/ENT
  { code: "H10.9", label: "Conjunctivitis, unspecified" },
  { code: "H66.90", label: "Otitis media, unspecified, unspecified ear" },
  { code: "H81.10", label: "Benign paroxysmal vertigo, unspecified ear" },
  { code: "J01.90", label: "Acute sinusitis, unspecified" },
  { code: "J02.9", label: "Acute pharyngitis, unspecified" },
  { code: "J03.90", label: "Acute tonsillitis, unspecified" },
  { code: "J04.0", label: "Acute laryngitis" },

  // Cardiovascular
  { code: "I10", label: "Essential (primary) hypertension" },
  { code: "I16.0", label: "Hypertensive urgency" },
  { code: "I20.9", label: "Angina pectoris, unspecified" },
  { code: "I21.4", label: "Non-ST elevation myocardial infarction" },
  { code: "I25.10", label: "Atherosclerotic heart disease of native coronary artery without angina pectoris" },
  { code: "I26.99", label: "Other pulmonary embolism without acute cor pulmonale" },
  { code: "I48.91", label: "Unspecified atrial fibrillation" },
  { code: "I50.9", label: "Heart failure, unspecified" },
  { code: "I63.9", label: "Cerebral infarction, unspecified" },
  { code: "I95.9", label: "Hypotension, unspecified" },
  { code: "R00.0", label: "Tachycardia, unspecified" },
  { code: "R07.2", label: "Precordial pain" },
  { code: "R07.9", label: "Chest pain, unspecified" },
  { code: "R55", label: "Syncope and collapse" },
  { code: "Z86.73", label: "Personal history of transient ischemic attack and cerebral infarction without residual deficits" },

  // Respiratory
  { code: "J00", label: "Acute nasopharyngitis (common cold)" },
  { code: "J06.9", label: "Acute upper respiratory infection, unspecified" },
  { code: "J09.X2", label: "Influenza due to identified novel influenza A virus with other respiratory manifestations" },
  { code: "J11.1", label: "Influenza due to unidentified influenza virus with other respiratory manifestations" },
  { code: "J12.9", label: "Viral pneumonia, unspecified" },
  { code: "J18.9", label: "Pneumonia, unspecified organism" },
  { code: "J20.9", label: "Acute bronchitis, unspecified" },
  { code: "J44.1", label: "Chronic obstructive pulmonary disease with acute exacerbation" },
  { code: "J45.901", label: "Unspecified asthma with (acute) exacerbation" },
  { code: "J45.909", label: "Unspecified asthma, uncomplicated" },
  { code: "J96.00", label: "Acute respiratory failure, unspecified whether with hypoxia or hypercapnia" },
  { code: "R05.9", label: "Cough, unspecified" },
  { code: "R06.00", label: "Dyspnea, unspecified" },
  { code: "R06.02", label: "Shortness of breath" },
  { code: "R09.81", label: "Nasal congestion" },

  // GI/hepatobiliary
  { code: "K21.9", label: "Gastro-esophageal reflux disease without esophagitis" },
  { code: "K29.70", label: "Gastritis, unspecified, without bleeding" },
  { code: "K35.80", label: "Unspecified acute appendicitis" },
  { code: "K52.9", label: "Noninfective gastroenteritis and colitis, unspecified" },
  { code: "K56.609", label: "Unspecified intestinal obstruction, unspecified as to partial versus complete obstruction" },
  { code: "K57.92", label: "Diverticulitis of intestine, part unspecified, without perforation or abscess without bleeding" },
  { code: "K59.00", label: "Constipation, unspecified" },
  { code: "K62.5", label: "Hemorrhage of anus and rectum" },
  { code: "K64.9", label: "Unspecified hemorrhoids" },
  { code: "K70.30", label: "Alcoholic cirrhosis of liver without ascites" },
  { code: "K74.60", label: "Unspecified cirrhosis of liver" },
  { code: "K80.20", label: "Calculus of gallbladder without cholecystitis without obstruction" },
  { code: "K81.0", label: "Acute cholecystitis" },
  { code: "K85.90", label: "Acute pancreatitis, unspecified" },
  { code: "R10.11", label: "Right upper quadrant pain" },
  { code: "R10.13", label: "Epigastric pain" },
  { code: "R10.31", label: "Right lower quadrant pain" },
  { code: "R10.32", label: "Left lower quadrant pain" },
  { code: "R10.9", label: "Unspecified abdominal pain" },
  { code: "R11.0", label: "Nausea" },
  { code: "R11.10", label: "Vomiting, unspecified" },
  { code: "R11.2", label: "Nausea with vomiting, unspecified" },
  { code: "R19.7", label: "Diarrhea, unspecified" },

  // GU/renal/reproductive
  { code: "N17.9", label: "Acute kidney failure, unspecified" },
  { code: "N18.9", label: "Chronic kidney disease, unspecified" },
  { code: "N20.0", label: "Calculus of kidney" },
  { code: "N23", label: "Unspecified renal colic" },
  { code: "N39.0", label: "Urinary tract infection, site not specified" },
  { code: "N39.3", label: "Stress incontinence (female) (male)" },
  { code: "N40.1", label: "Benign prostatic hyperplasia with lower urinary tract symptoms" },
  { code: "N45.1", label: "Epididymitis" },
  { code: "N76.0", label: "Acute vaginitis" },
  { code: "N93.9", label: "Abnormal uterine and vaginal bleeding, unspecified" },
  { code: "R30.0", label: "Dysuria" },
  { code: "R31.9", label: "Hematuria, unspecified" },
  { code: "R33.9", label: "Retention of urine, unspecified" },

  // Obstetric
  { code: "O21.9", label: "Vomiting of pregnancy, unspecified" },
  { code: "O26.899", label: "Other specified pregnancy related conditions, unspecified trimester" },
  { code: "O80", label: "Encounter for full-term uncomplicated delivery" },
  { code: "Z32.01", label: "Encounter for pregnancy test, result positive" },
  { code: "Z34.90", label: "Encounter for supervision of normal pregnancy, unspecified, unspecified trimester" },

  // Musculoskeletal
  { code: "M25.511", label: "Pain in right shoulder" },
  { code: "M25.512", label: "Pain in left shoulder" },
  { code: "M25.561", label: "Pain in right knee" },
  { code: "M25.562", label: "Pain in left knee" },
  { code: "M54.2", label: "Cervicalgia" },
  { code: "M54.50", label: "Low back pain, unspecified" },
  { code: "M54.6", label: "Pain in thoracic spine" },
  { code: "M62.830", label: "Muscle spasm of back" },
  { code: "M79.1", label: "Myalgia" },
  { code: "M79.671", label: "Pain in right foot" },
  { code: "M79.672", label: "Pain in left foot" },
  { code: "M10.9", label: "Gout, unspecified" },
  { code: "M19.90", label: "Unspecified osteoarthritis, unspecified site" },

  // Skin
  { code: "L02.91", label: "Cutaneous abscess, unspecified" },
  { code: "L03.90", label: "Cellulitis, unspecified" },
  { code: "L20.9", label: "Atopic dermatitis, unspecified" },
  { code: "L23.9", label: "Allergic contact dermatitis, unspecified cause" },
  { code: "L29.9", label: "Pruritus, unspecified" },
  { code: "L50.9", label: "Urticaria, unspecified" },
  { code: "L70.0", label: "Acne vulgaris" },
  { code: "R21", label: "Rash and other nonspecific skin eruption" },

  // Symptoms/general
  { code: "R41.82", label: "Altered mental status, unspecified" },
  { code: "R50.9", label: "Fever, unspecified" },
  { code: "R53.1", label: "Weakness" },
  { code: "R53.81", label: "Other malaise" },
  { code: "R53.83", label: "Other fatigue" },
  { code: "R60.0", label: "Localized edema" },
  { code: "R63.0", label: "Anorexia" },
  { code: "R63.4", label: "Abnormal weight loss" },
  { code: "R73.9", label: "Hyperglycemia, unspecified" },
  { code: "R79.89", label: "Other specified abnormal findings of blood chemistry" },

  // Injury/trauma
  { code: "S01.81XA", label: "Laceration without foreign body of other part of head, initial encounter" },
  { code: "S06.0X0A", label: "Concussion without loss of consciousness, initial encounter" },
  { code: "S09.90XA", label: "Unspecified injury of head, initial encounter" },
  { code: "S16.1XXA", label: "Strain of muscle, fascia and tendon at neck level, initial encounter" },
  { code: "S29.012A", label: "Strain of muscle and tendon of back wall of thorax, initial encounter" },
  { code: "S39.012A", label: "Strain of muscle, fascia and tendon of lower back, initial encounter" },
  { code: "S42.201A", label: "Unspecified fracture of upper end of right humerus, initial encounter for closed fracture" },
  { code: "S52.501A", label: "Unspecified fracture of lower end of right radius, initial encounter" },
  { code: "S62.101A", label: "Unspecified fracture of right wrist and hand, initial encounter for closed fracture" },
  { code: "S72.001A", label: "Fracture of unspecified part of neck of right femur, initial encounter for closed fracture" },
  { code: "S82.001A", label: "Fracture of right patella, initial encounter" },
  { code: "S82.101A", label: "Unspecified fracture of upper end of right tibia, initial encounter for closed fracture" },
  { code: "S91.301A", label: "Unspecified open wound, right foot, initial encounter" },
  { code: "T14.8XXA", label: "Other injury of unspecified body region, initial encounter" },
  { code: "T30.0", label: "Burn of unspecified body region, unspecified degree" },
  { code: "T50.901A", label: "Poisoning by unspecified drugs, medicaments and biological substances, accidental, initial encounter" },
  { code: "T63.441A", label: "Toxic effect of venom of bees, accidental, initial encounter" },

  // External causes
  { code: "V43.52XA", label: "Car driver injured in collision with sport utility vehicle in traffic accident, initial encounter" },
  { code: "W01.0XXA", label: "Fall on same level from slipping, tripping and stumbling without subsequent striking against object, initial encounter" },
  { code: "W10.9XXA", label: "Fall on and from stairs and steps, unspecified, initial encounter" },
  { code: "W19.XXXA", label: "Unspecified fall, initial encounter" },
  { code: "W54.0XXA", label: "Bitten by dog, initial encounter" },
  { code: "W55.01XA", label: "Bitten by cat, initial encounter" },
  { code: "X58.XXXA", label: "Exposure to other specified factors, initial encounter" },
  { code: "Y92.009", label: "Unspecified place in unspecified non-institutional residence as the place of occurrence of the external cause" },

  // Z-codes and follow-up
  { code: "Z00.00", label: "Encounter for general adult medical examination without abnormal findings" },
  { code: "Z09", label: "Encounter for follow-up examination after completed treatment for conditions other than malignant neoplasm" },
  { code: "Z13.1", label: "Encounter for screening for diabetes mellitus" },
  { code: "Z20.822", label: "Contact with and (suspected) exposure to COVID-19" },
  { code: "Z23", label: "Encounter for immunization" },
  { code: "Z51.89", label: "Encounter for other specified aftercare" },
  { code: "Z71.9", label: "Counseling, unspecified" },
  { code: "Z79.01", label: "Long term (current) use of anticoagulants" },
  { code: "Z79.4", label: "Long term (current) use of insulin" },
  { code: "Z87.891", label: "Personal history of nicotine dependence" },
  { code: "Z91.14", label: "Patient's other noncompliance with medication regimen" },
  { code: "Z91.81", label: "History of falling" },
  { code: "Z99.81", label: "Dependence on supplemental oxygen" },

  // Pediatric/common acute
  { code: "H65.93", label: "Unspecified nonsuppurative otitis media, bilateral" },
  { code: "J21.9", label: "Acute bronchiolitis, unspecified" },
  { code: "J35.1", label: "Hypertrophy of tonsils" },
  { code: "K00.7", label: "Teething syndrome" },
  { code: "R50.81", label: "Fever presenting with conditions classified elsewhere" },
];
