export type InstitutionDepartmentSeed = {
  name: string;
  sort_order: number;
  is_active: boolean;
};

/** Canonical baseline department catalog shown and seeded for every institution. */
export const PRESET_INSTITUTION_DEPARTMENTS: InstitutionDepartmentSeed[] = [
  { name: "Emergency Medicine (EM)", sort_order: 100, is_active: true },
  { name: "Pediatric Emergency Medicine", sort_order: 105, is_active: true },
  { name: "Medical Toxicology", sort_order: 110, is_active: true },
  { name: "Sports Medicine (Emergency Medicine)", sort_order: 115, is_active: true },
  { name: "Undersea & Hyperbaric Medicine", sort_order: 120, is_active: true },
  { name: "Level 1 Trauma / Trauma Center", sort_order: 125, is_active: true },
  { name: "Internal Medicine (IM)", sort_order: 200, is_active: true },
  { name: "Cardiology", sort_order: 205, is_active: true },
  { name: "Gastroenterology (GI)", sort_order: 210, is_active: true },
  { name: "Nephrology", sort_order: 215, is_active: true },
  { name: "Pulmonology", sort_order: 220, is_active: true },
  { name: "Endocrinology", sort_order: 225, is_active: true },
  { name: "Rheumatology", sort_order: 230, is_active: true },
  { name: "Infectious Disease (ID)", sort_order: 235, is_active: true },
  { name: "Hematology", sort_order: 238, is_active: true },
  { name: "General Surgery (GS)", sort_order: 300, is_active: true },
  { name: "Trauma Surgery", sort_order: 305, is_active: true },
  { name: "Surgical Critical Care", sort_order: 310, is_active: true },
  { name: "Pediatric Surgery", sort_order: 315, is_active: true },
  { name: "Surgical Oncology", sort_order: 320, is_active: true },
  { name: "Vascular Surgery", sort_order: 325, is_active: true },
  { name: "Pediatrics (Peds)", sort_order: 400, is_active: true },
  { name: "Neonatology (NICU)", sort_order: 405, is_active: true },
  { name: "Pediatric Cardiology", sort_order: 410, is_active: true },
  { name: "Pediatric Hematology-Oncology", sort_order: 415, is_active: true },
  { name: "Adolescent Medicine", sort_order: 420, is_active: true },
  { name: "Obstetrics & Gynecology (OB/GYN)", sort_order: 500, is_active: true },
  { name: "Maternal-Fetal Medicine (High-Risk Pregnancy)", sort_order: 505, is_active: true },
  { name: "Reproductive Endocrinology (Infertility)", sort_order: 510, is_active: true },
  { name: "Gynecologic Oncology", sort_order: 515, is_active: true },
  { name: "Labor & Delivery", sort_order: 520, is_active: true },
  { name: "Orthopedic Surgery", sort_order: 600, is_active: true },
  { name: "Neurological Surgery (Neurosurgery)", sort_order: 605, is_active: true },
  { name: "Anesthesiology", sort_order: 610, is_active: true },
  { name: "Critical Care Anesthesiology", sort_order: 612, is_active: true },
  { name: "Pain Medicine (Anesthesiology)", sort_order: 615, is_active: true },
  { name: "Ophthalmology", sort_order: 620, is_active: true },
  { name: "Otolaryngology (ENT) — Head & Neck Surgery", sort_order: 625, is_active: true },
  { name: "Urology", sort_order: 630, is_active: true },
  { name: "Plastic & Reconstructive Surgery", sort_order: 635, is_active: true },
  { name: "Cardiothoracic Surgery", sort_order: 640, is_active: true },
  { name: "Operating Room (OR)", sort_order: 645, is_active: true },
  { name: "Post-Anesthesia Care Unit (PACU)", sort_order: 650, is_active: true },
  { name: "Diagnostic Radiology (X-ray, CT, MRI, Ultrasound)", sort_order: 700, is_active: true },
  { name: "Interventional Radiology", sort_order: 705, is_active: true },
  { name: "Anatomic Pathology (Biopsies & Autopsy)", sort_order: 710, is_active: true },
  { name: "Clinical Pathology — Lab (Blood Bank, Microbiology, Chemistry)", sort_order: 715, is_active: true },
  { name: "Blood Bank / Transfusion Services", sort_order: 720, is_active: true },
  { name: "Nuclear Medicine", sort_order: 725, is_active: true },
  { name: "Neurology", sort_order: 800, is_active: true },
  { name: "Psychiatry", sort_order: 805, is_active: true },
  { name: "Addiction Medicine", sort_order: 810, is_active: true },
  { name: "Child & Adolescent Psychiatry", sort_order: 815, is_active: true },
  { name: "Dermatology", sort_order: 820, is_active: true },
  { name: "Physical Medicine & Rehabilitation (PM&R) / Physiatry", sort_order: 825, is_active: true },
  { name: "Radiation Oncology", sort_order: 830, is_active: true },
  { name: "Medical Oncology (Chemotherapy)", sort_order: 835, is_active: true },
  { name: "Medical Genetics", sort_order: 840, is_active: true },
  { name: "Intensive Care Unit (ICU)", sort_order: 900, is_active: true },
  { name: "Critical Care", sort_order: 905, is_active: true },
  { name: "Telemetry", sort_order: 910, is_active: true },
  { name: "Step-Down Unit", sort_order: 915, is_active: true },
  { name: "Medical-Surgical Unit", sort_order: 920, is_active: true },
  { name: "Pharmacy", sort_order: 950, is_active: true },
  { name: "Physical Therapy", sort_order: 955, is_active: true },
  { name: "Occupational Therapy", sort_order: 960, is_active: true },
  { name: "Speech-Language Pathology", sort_order: 965, is_active: true },
  { name: "Respiratory Therapy", sort_order: 970, is_active: true },
  { name: "Nutrition & Dietary", sort_order: 975, is_active: true },
  { name: "Social Work / Case Management", sort_order: 980, is_active: true },
  { name: "Family Medicine", sort_order: 1000, is_active: true },
  { name: "Primary Care", sort_order: 1005, is_active: true },
  { name: "Geriatrics", sort_order: 1010, is_active: true },
  { name: "Palliative Care / Hospice", sort_order: 1015, is_active: true },
  { name: "Infection Prevention & Control", sort_order: 1020, is_active: true },
  { name: "Quality & Patient Safety", sort_order: 1025, is_active: true },
  { name: "Hospital Administration", sort_order: 1030, is_active: true },
  { name: "Health Information Management", sort_order: 1035, is_active: true },
  { name: "Facilities & Engineering", sort_order: 1040, is_active: true },
  { name: "Environmental Services", sort_order: 1045, is_active: true },
  { name: "Security", sort_order: 1050, is_active: true },
  { name: "Chaplaincy / Spiritual Care", sort_order: 1055, is_active: true },
];
