export type MedicationCategory =
  | "all"
  | "analgesics"
  | "antibiotics"
  | "cardiovascular"
  | "respiratory"
  | "endocrine"
  | "gi"
  | "neuro_psych"
  | "critical_care"
  | "anticoagulation"
  | "obgyn"
  | "renal_urology"
  | "infectious_antiviral"
  | "misc";

export interface MedicationItem {
  name: string;
  aliases?: string[];
  category: Exclude<MedicationCategory, "all">;
  controlled: boolean;
  defaultRoute?: string;
  defaultFrequency?: string;
}

export const MEDICATION_CATEGORY_LABELS: Record<MedicationCategory, string> = {
  all: "All",
  analgesics: "Pain / Sedation",
  antibiotics: "Antibiotics",
  cardiovascular: "Cardiovascular",
  respiratory: "Respiratory",
  endocrine: "Endocrine / Metabolic",
  gi: "GI / Hepatic",
  neuro_psych: "Neuro / Psych",
  critical_care: "Critical Care / ED",
  anticoagulation: "Anticoagulation / Hematology",
  obgyn: "OB/GYN",
  renal_urology: "Renal / Urology",
  infectious_antiviral: "Antiviral / ID Adjuncts",
  misc: "Other",
};

export const MEDICATION_CATEGORIES: MedicationCategory[] = [
  "all",
  "analgesics",
  "antibiotics",
  "cardiovascular",
  "respiratory",
  "endocrine",
  "gi",
  "neuro_psych",
  "critical_care",
  "anticoagulation",
  "obgyn",
  "renal_urology",
  "infectious_antiviral",
  "misc",
];

// Large curated formulary for realistic simulation UX.
// This is intentionally broad, but can be expanded further over time.
export const MEDICATION_FORMULARY: MedicationItem[] = [
  { name: "Acetaminophen", aliases: ["Tylenol"], category: "analgesics", controlled: false, defaultRoute: "PO", defaultFrequency: "Q6H PRN" },
  { name: "Ibuprofen", aliases: ["Motrin", "Advil"], category: "analgesics", controlled: false, defaultRoute: "PO", defaultFrequency: "Q8H PRN" },
  { name: "Naproxen", aliases: ["Aleve"], category: "analgesics", controlled: false, defaultRoute: "PO", defaultFrequency: "BID PRN" },
  { name: "Ketorolac", aliases: ["Toradol"], category: "analgesics", controlled: false, defaultRoute: "IV", defaultFrequency: "Q6H PRN" },
  { name: "Diclofenac", aliases: ["Voltaren"], category: "analgesics", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Meloxicam", aliases: ["Mobic"], category: "analgesics", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Celecoxib", aliases: ["Celebrex"], category: "analgesics", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Lidocaine Patch", aliases: ["Lidoderm"], category: "analgesics", controlled: false, defaultRoute: "Topical", defaultFrequency: "Daily" },
  { name: "Tramadol", aliases: ["Ultram"], category: "analgesics", controlled: true, defaultRoute: "PO", defaultFrequency: "Q6H PRN" },
  { name: "Codeine", aliases: ["Tylenol #3"], category: "analgesics", controlled: true, defaultRoute: "PO", defaultFrequency: "Q4H PRN" },
  { name: "Hydrocodone/Acetaminophen", aliases: ["Norco"], category: "analgesics", controlled: true, defaultRoute: "PO", defaultFrequency: "Q6H PRN" },
  { name: "Oxycodone", aliases: ["Roxicodone"], category: "analgesics", controlled: true, defaultRoute: "PO", defaultFrequency: "Q6H PRN" },
  { name: "Oxycodone/Acetaminophen", aliases: ["Percocet"], category: "analgesics", controlled: true, defaultRoute: "PO", defaultFrequency: "Q6H PRN" },
  { name: "Morphine", aliases: ["MS Contin"], category: "analgesics", controlled: true, defaultRoute: "IV", defaultFrequency: "Q4H PRN" },
  { name: "Hydromorphone", aliases: ["Dilaudid"], category: "analgesics", controlled: true, defaultRoute: "IV", defaultFrequency: "Q4H PRN" },
  { name: "Fentanyl", aliases: ["Sublimaze"], category: "analgesics", controlled: true, defaultRoute: "IV", defaultFrequency: "Q1H PRN" },
  { name: "Methadone", aliases: ["Dolophine"], category: "analgesics", controlled: true, defaultRoute: "PO", defaultFrequency: "Q8H" },
  { name: "Buprenorphine", aliases: ["Subutex"], category: "analgesics", controlled: true, defaultRoute: "SL", defaultFrequency: "Daily" },
  { name: "Cyclobenzaprine", aliases: ["Flexeril"], category: "analgesics", controlled: false, defaultRoute: "PO", defaultFrequency: "TID PRN" },
  { name: "Methocarbamol", aliases: ["Robaxin"], category: "analgesics", controlled: false, defaultRoute: "PO", defaultFrequency: "QID PRN" },

  { name: "Amoxicillin", aliases: ["Amoxil"], category: "antibiotics", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Amoxicillin/Clavulanate", aliases: ["Augmentin"], category: "antibiotics", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Penicillin VK", aliases: ["Pen-VK"], category: "antibiotics", controlled: false, defaultRoute: "PO", defaultFrequency: "QID" },
  { name: "Ampicillin", category: "antibiotics", controlled: false, defaultRoute: "IV", defaultFrequency: "Q6H" },
  { name: "Piperacillin/Tazobactam", aliases: ["Zosyn"], category: "antibiotics", controlled: false, defaultRoute: "IV", defaultFrequency: "Q6H" },
  { name: "Cefazolin", aliases: ["Ancef"], category: "antibiotics", controlled: false, defaultRoute: "IV", defaultFrequency: "Q8H" },
  { name: "Cephalexin", aliases: ["Keflex"], category: "antibiotics", controlled: false, defaultRoute: "PO", defaultFrequency: "QID" },
  { name: "Ceftriaxone", aliases: ["Rocephin"], category: "antibiotics", controlled: false, defaultRoute: "IV", defaultFrequency: "Q24H" },
  { name: "Cefepime", aliases: ["Maxipime"], category: "antibiotics", controlled: false, defaultRoute: "IV", defaultFrequency: "Q8H" },
  { name: "Ceftazidime", aliases: ["Fortaz"], category: "antibiotics", controlled: false, defaultRoute: "IV", defaultFrequency: "Q8H" },
  { name: "Cefdinir", aliases: ["Omnicef"], category: "antibiotics", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Azithromycin", aliases: ["Zithromax"], category: "antibiotics", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Clarithromycin", aliases: ["Biaxin"], category: "antibiotics", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Doxycycline", aliases: ["Vibramycin"], category: "antibiotics", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Minocycline", aliases: ["Minocin"], category: "antibiotics", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Clindamycin", aliases: ["Cleocin"], category: "antibiotics", controlled: false, defaultRoute: "IV", defaultFrequency: "Q8H" },
  { name: "Metronidazole", aliases: ["Flagyl"], category: "antibiotics", controlled: false, defaultRoute: "IV", defaultFrequency: "Q8H" },
  { name: "Vancomycin", aliases: ["Vancocin"], category: "antibiotics", controlled: false, defaultRoute: "IV", defaultFrequency: "Per protocol" },
  { name: "Linezolid", aliases: ["Zyvox"], category: "antibiotics", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Levofloxacin", aliases: ["Levaquin"], category: "antibiotics", controlled: false, defaultRoute: "IV", defaultFrequency: "Q24H" },
  { name: "Ciprofloxacin", aliases: ["Cipro"], category: "antibiotics", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Trimethoprim/Sulfamethoxazole", aliases: ["Bactrim"], category: "antibiotics", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Nitrofurantoin", aliases: ["Macrobid"], category: "antibiotics", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Meropenem", aliases: ["Merrem"], category: "antibiotics", controlled: false, defaultRoute: "IV", defaultFrequency: "Q8H" },
  { name: "Ertapenem", aliases: ["Invanz"], category: "antibiotics", controlled: false, defaultRoute: "IV", defaultFrequency: "Q24H" },

  { name: "Lisinopril", aliases: ["Prinivil"], category: "cardiovascular", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Losartan", aliases: ["Cozaar"], category: "cardiovascular", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Valsartan", aliases: ["Diovan"], category: "cardiovascular", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Amlodipine", aliases: ["Norvasc"], category: "cardiovascular", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Nifedipine", aliases: ["Procardia"], category: "cardiovascular", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Metoprolol", aliases: ["Lopressor"], category: "cardiovascular", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Carvedilol", aliases: ["Coreg"], category: "cardiovascular", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Labetalol", aliases: ["Normodyne"], category: "cardiovascular", controlled: false, defaultRoute: "IV", defaultFrequency: "Q10MIN PRN" },
  { name: "Hydralazine", aliases: ["Apresoline"], category: "cardiovascular", controlled: false, defaultRoute: "IV", defaultFrequency: "Q6H PRN" },
  { name: "Nitroglycerin", aliases: ["NTG"], category: "cardiovascular", controlled: false, defaultRoute: "SL", defaultFrequency: "Q5MIN PRN" },
  { name: "Isosorbide Mononitrate", aliases: ["Imdur"], category: "cardiovascular", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Diltiazem", aliases: ["Cardizem"], category: "cardiovascular", controlled: false, defaultRoute: "IV", defaultFrequency: "Per protocol" },
  { name: "Verapamil", aliases: ["Calan"], category: "cardiovascular", controlled: false, defaultRoute: "PO", defaultFrequency: "TID" },
  { name: "Amiodarone", aliases: ["Cordarone"], category: "cardiovascular", controlled: false, defaultRoute: "IV", defaultFrequency: "Per protocol" },
  { name: "Adenosine", aliases: ["Adenocard"], category: "cardiovascular", controlled: false, defaultRoute: "IV", defaultFrequency: "Once PRN" },
  { name: "Atorvastatin", aliases: ["Lipitor"], category: "cardiovascular", controlled: false, defaultRoute: "PO", defaultFrequency: "Nightly" },
  { name: "Rosuvastatin", aliases: ["Crestor"], category: "cardiovascular", controlled: false, defaultRoute: "PO", defaultFrequency: "Nightly" },
  { name: "Furosemide", aliases: ["Lasix"], category: "cardiovascular", controlled: false, defaultRoute: "IV", defaultFrequency: "Daily" },
  { name: "Bumetanide", aliases: ["Bumex"], category: "cardiovascular", controlled: false, defaultRoute: "IV", defaultFrequency: "Daily" },
  { name: "Spironolactone", aliases: ["Aldactone"], category: "cardiovascular", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Digoxin", aliases: ["Lanoxin"], category: "cardiovascular", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },

  { name: "Albuterol", aliases: ["Ventolin"], category: "respiratory", controlled: false, defaultRoute: "Neb", defaultFrequency: "Q4H PRN" },
  { name: "Ipratropium", aliases: ["Atrovent"], category: "respiratory", controlled: false, defaultRoute: "Neb", defaultFrequency: "Q6H" },
  { name: "Levalbuterol", aliases: ["Xopenex"], category: "respiratory", controlled: false, defaultRoute: "Neb", defaultFrequency: "Q6H PRN" },
  { name: "Budesonide", aliases: ["Pulmicort"], category: "respiratory", controlled: false, defaultRoute: "Neb", defaultFrequency: "BID" },
  { name: "Fluticasone/Salmeterol", aliases: ["Advair"], category: "respiratory", controlled: false, defaultRoute: "Inhaled", defaultFrequency: "BID" },
  { name: "Tiotropium", aliases: ["Spiriva"], category: "respiratory", controlled: false, defaultRoute: "Inhaled", defaultFrequency: "Daily" },
  { name: "Montelukast", aliases: ["Singulair"], category: "respiratory", controlled: false, defaultRoute: "PO", defaultFrequency: "Nightly" },
  { name: "Prednisone", aliases: ["Deltasone"], category: "respiratory", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Methylprednisolone", aliases: ["Solu-Medrol"], category: "respiratory", controlled: false, defaultRoute: "IV", defaultFrequency: "Q8H" },

  { name: "Insulin Lispro", aliases: ["Humalog"], category: "endocrine", controlled: false, defaultRoute: "SC", defaultFrequency: "Per protocol" },
  { name: "Insulin Aspart", aliases: ["Novolog"], category: "endocrine", controlled: false, defaultRoute: "SC", defaultFrequency: "Per protocol" },
  { name: "Insulin Glargine", aliases: ["Lantus"], category: "endocrine", controlled: false, defaultRoute: "SC", defaultFrequency: "Nightly" },
  { name: "Insulin Detemir", aliases: ["Levemir"], category: "endocrine", controlled: false, defaultRoute: "SC", defaultFrequency: "Daily" },
  { name: "Metformin", aliases: ["Glucophage"], category: "endocrine", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Glipizide", aliases: ["Glucotrol"], category: "endocrine", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Levothyroxine", aliases: ["Synthroid"], category: "endocrine", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Hydrocortisone", aliases: ["Solu-Cortef"], category: "endocrine", controlled: false, defaultRoute: "IV", defaultFrequency: "Q6H" },
  { name: "Dexamethasone", aliases: ["Decadron"], category: "endocrine", controlled: false, defaultRoute: "IV", defaultFrequency: "Q12H" },
  { name: "Calcium Gluconate", category: "endocrine", controlled: false, defaultRoute: "IV", defaultFrequency: "Once PRN" },

  { name: "Ondansetron", aliases: ["Zofran"], category: "gi", controlled: false, defaultRoute: "IV", defaultFrequency: "Q8H PRN" },
  { name: "Promethazine", aliases: ["Phenergan"], category: "gi", controlled: false, defaultRoute: "IV", defaultFrequency: "Q6H PRN" },
  { name: "Metoclopramide", aliases: ["Reglan"], category: "gi", controlled: false, defaultRoute: "IV", defaultFrequency: "Q6H PRN" },
  { name: "Pantoprazole", aliases: ["Protonix"], category: "gi", controlled: false, defaultRoute: "IV", defaultFrequency: "Daily" },
  { name: "Omeprazole", aliases: ["Prilosec"], category: "gi", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Famotidine", aliases: ["Pepcid"], category: "gi", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Sucralfate", aliases: ["Carafate"], category: "gi", controlled: false, defaultRoute: "PO", defaultFrequency: "QID" },
  { name: "Lactulose", category: "gi", controlled: false, defaultRoute: "PO", defaultFrequency: "BID PRN" },
  { name: "Polyethylene Glycol", aliases: ["Miralax"], category: "gi", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily PRN" },
  { name: "Senna", aliases: ["Senokot"], category: "gi", controlled: false, defaultRoute: "PO", defaultFrequency: "Nightly PRN" },
  { name: "Docusate", aliases: ["Colace"], category: "gi", controlled: false, defaultRoute: "PO", defaultFrequency: "BID PRN" },
  { name: "Loperamide", aliases: ["Imodium"], category: "gi", controlled: false, defaultRoute: "PO", defaultFrequency: "PRN" },

  { name: "Sertraline", aliases: ["Zoloft"], category: "neuro_psych", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Fluoxetine", aliases: ["Prozac"], category: "neuro_psych", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Escitalopram", aliases: ["Lexapro"], category: "neuro_psych", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Bupropion", aliases: ["Wellbutrin"], category: "neuro_psych", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Mirtazapine", aliases: ["Remeron"], category: "neuro_psych", controlled: false, defaultRoute: "PO", defaultFrequency: "Nightly" },
  { name: "Trazodone", aliases: ["Desyrel"], category: "neuro_psych", controlled: false, defaultRoute: "PO", defaultFrequency: "Nightly PRN" },
  { name: "Haloperidol", aliases: ["Haldol"], category: "neuro_psych", controlled: false, defaultRoute: "IV", defaultFrequency: "Q6H PRN" },
  { name: "Olanzapine", aliases: ["Zyprexa"], category: "neuro_psych", controlled: false, defaultRoute: "PO", defaultFrequency: "Nightly" },
  { name: "Quetiapine", aliases: ["Seroquel"], category: "neuro_psych", controlled: false, defaultRoute: "PO", defaultFrequency: "Nightly" },
  { name: "Risperidone", aliases: ["Risperdal"], category: "neuro_psych", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Levetiracetam", aliases: ["Keppra"], category: "neuro_psych", controlled: false, defaultRoute: "IV", defaultFrequency: "BID" },
  { name: "Valproic Acid", aliases: ["Depakote"], category: "neuro_psych", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Phenytoin", aliases: ["Dilantin"], category: "neuro_psych", controlled: false, defaultRoute: "IV", defaultFrequency: "Daily" },
  { name: "Gabapentin", aliases: ["Neurontin"], category: "neuro_psych", controlled: false, defaultRoute: "PO", defaultFrequency: "TID" },
  { name: "Pregabalin", aliases: ["Lyrica"], category: "neuro_psych", controlled: true, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Lorazepam", aliases: ["Ativan"], category: "neuro_psych", controlled: true, defaultRoute: "IV", defaultFrequency: "Q6H PRN" },
  { name: "Diazepam", aliases: ["Valium"], category: "neuro_psych", controlled: true, defaultRoute: "IV", defaultFrequency: "Q8H PRN" },
  { name: "Midazolam", aliases: ["Versed"], category: "neuro_psych", controlled: true, defaultRoute: "IV", defaultFrequency: "PRN" },
  { name: "Alprazolam", aliases: ["Xanax"], category: "neuro_psych", controlled: true, defaultRoute: "PO", defaultFrequency: "TID PRN" },
  { name: "Clonazepam", aliases: ["Klonopin"], category: "neuro_psych", controlled: true, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Zolpidem", aliases: ["Ambien"], category: "neuro_psych", controlled: true, defaultRoute: "PO", defaultFrequency: "Nightly PRN" },
  { name: "Dextroamphetamine/Amphetamine", aliases: ["Adderall"], category: "neuro_psych", controlled: true, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Methylphenidate", aliases: ["Ritalin"], category: "neuro_psych", controlled: true, defaultRoute: "PO", defaultFrequency: "BID" },

  { name: "Epinephrine", aliases: ["Adrenalin"], category: "critical_care", controlled: false, defaultRoute: "IM", defaultFrequency: "Once PRN" },
  { name: "Norepinephrine", aliases: ["Levophed"], category: "critical_care", controlled: false, defaultRoute: "IV", defaultFrequency: "Continuous" },
  { name: "Phenylephrine", aliases: ["Neo-Synephrine"], category: "critical_care", controlled: false, defaultRoute: "IV", defaultFrequency: "Continuous" },
  { name: "Vasopressin", aliases: ["Pitressin"], category: "critical_care", controlled: false, defaultRoute: "IV", defaultFrequency: "Continuous" },
  { name: "Dopamine", aliases: ["Intropin"], category: "critical_care", controlled: false, defaultRoute: "IV", defaultFrequency: "Continuous" },
  { name: "Dobutamine", aliases: ["Dobutrex"], category: "critical_care", controlled: false, defaultRoute: "IV", defaultFrequency: "Continuous" },
  { name: "Propofol", aliases: ["Diprivan"], category: "critical_care", controlled: false, defaultRoute: "IV", defaultFrequency: "Continuous" },
  { name: "Ketamine", aliases: ["Ketalar"], category: "critical_care", controlled: true, defaultRoute: "IV", defaultFrequency: "PRN" },
  { name: "Etomidate", aliases: ["Amidate"], category: "critical_care", controlled: false, defaultRoute: "IV", defaultFrequency: "Once" },
  { name: "Rocuronium", aliases: ["Zemuron"], category: "critical_care", controlled: false, defaultRoute: "IV", defaultFrequency: "Once" },
  { name: "Succinylcholine", aliases: ["Anectine"], category: "critical_care", controlled: false, defaultRoute: "IV", defaultFrequency: "Once" },
  { name: "Naloxone", aliases: ["Narcan"], category: "critical_care", controlled: false, defaultRoute: "IV", defaultFrequency: "PRN" },
  { name: "Flumazenil", aliases: ["Romazicon"], category: "critical_care", controlled: false, defaultRoute: "IV", defaultFrequency: "PRN" },
  { name: "Dextrose 50%", aliases: ["D50"], category: "critical_care", controlled: false, defaultRoute: "IV", defaultFrequency: "PRN" },
  { name: "Glucagon", aliases: ["GlucaGen"], category: "critical_care", controlled: false, defaultRoute: "IM", defaultFrequency: "PRN" },
  { name: "Calcium Chloride", category: "critical_care", controlled: false, defaultRoute: "IV", defaultFrequency: "PRN" },
  { name: "Sodium Bicarbonate", aliases: ["Bicarb"], category: "critical_care", controlled: false, defaultRoute: "IV", defaultFrequency: "PRN" },
  { name: "Magnesium Sulfate", aliases: ["Mag Sulf"], category: "critical_care", controlled: false, defaultRoute: "IV", defaultFrequency: "PRN" },
  { name: "Tranexamic Acid", aliases: ["TXA"], category: "critical_care", controlled: false, defaultRoute: "IV", defaultFrequency: "Q8H" },

  { name: "Heparin", category: "anticoagulation", controlled: false, defaultRoute: "IV", defaultFrequency: "Per protocol" },
  { name: "Enoxaparin", aliases: ["Lovenox"], category: "anticoagulation", controlled: false, defaultRoute: "SC", defaultFrequency: "Q12H" },
  { name: "Warfarin", aliases: ["Coumadin"], category: "anticoagulation", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Apixaban", aliases: ["Eliquis"], category: "anticoagulation", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Rivaroxaban", aliases: ["Xarelto"], category: "anticoagulation", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Dabigatran", aliases: ["Pradaxa"], category: "anticoagulation", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Clopidogrel", aliases: ["Plavix"], category: "anticoagulation", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Aspirin", aliases: ["ASA"], category: "anticoagulation", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },

  { name: "Oxytocin", aliases: ["Pitocin"], category: "obgyn", controlled: false, defaultRoute: "IV", defaultFrequency: "Per protocol" },
  { name: "Misoprostol", aliases: ["Cytotec"], category: "obgyn", controlled: false, defaultRoute: "PO", defaultFrequency: "Per protocol" },
  { name: "Methylergonovine", aliases: ["Methergine"], category: "obgyn", controlled: false, defaultRoute: "IM", defaultFrequency: "Q6H PRN" },
  { name: "Magnesium Sulfate (OB)", aliases: ["MgSO4"], category: "obgyn", controlled: false, defaultRoute: "IV", defaultFrequency: "Continuous" },
  { name: "Rho(D) Immune Globulin", aliases: ["RhoGAM"], category: "obgyn", controlled: false, defaultRoute: "IM", defaultFrequency: "Once" },

  { name: "Tamsulosin", aliases: ["Flomax"], category: "renal_urology", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Finasteride", aliases: ["Proscar"], category: "renal_urology", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Oxybutynin", aliases: ["Ditropan"], category: "renal_urology", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Potassium Chloride", aliases: ["KCl"], category: "renal_urology", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Sodium Zirconium Cyclosilicate", aliases: ["Lokelma"], category: "renal_urology", controlled: false, defaultRoute: "PO", defaultFrequency: "TID" },
  { name: "Sevelamer", aliases: ["Renvela"], category: "renal_urology", controlled: false, defaultRoute: "PO", defaultFrequency: "TID" },

  { name: "Oseltamivir", aliases: ["Tamiflu"], category: "infectious_antiviral", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Acyclovir", aliases: ["Zovirax"], category: "infectious_antiviral", controlled: false, defaultRoute: "IV", defaultFrequency: "Q8H" },
  { name: "Valacyclovir", aliases: ["Valtrex"], category: "infectious_antiviral", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Remdesivir", aliases: ["Veklury"], category: "infectious_antiviral", controlled: false, defaultRoute: "IV", defaultFrequency: "Daily" },
  { name: "Nirmatrelvir/Ritonavir", aliases: ["Paxlovid"], category: "infectious_antiviral", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },

  { name: "Diphenhydramine", aliases: ["Benadryl"], category: "misc", controlled: false, defaultRoute: "IV", defaultFrequency: "Q6H PRN" },
  { name: "Cetirizine", aliases: ["Zyrtec"], category: "misc", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Loratadine", aliases: ["Claritin"], category: "misc", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Hydroxyzine", aliases: ["Vistaril"], category: "misc", controlled: false, defaultRoute: "PO", defaultFrequency: "Q8H PRN" },
  { name: "Allopurinol", aliases: ["Zyloprim"], category: "misc", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Colchicine", aliases: ["Colcrys"], category: "misc", controlled: false, defaultRoute: "PO", defaultFrequency: "BID" },
  { name: "Nicotine Patch", aliases: ["Nicoderm"], category: "misc", controlled: false, defaultRoute: "Topical", defaultFrequency: "Daily" },
  { name: "Folic Acid", aliases: ["Folvite"], category: "misc", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Thiamine", aliases: ["Vitamin B1"], category: "misc", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Multivitamin", aliases: ["MVI"], category: "misc", controlled: false, defaultRoute: "PO", defaultFrequency: "Daily" },
  { name: "Cyanocobalamin", aliases: ["Vitamin B12"], category: "misc", controlled: false, defaultRoute: "IM", defaultFrequency: "Monthly" },
];
